version: 2
registries:
  github:
    type: git
    url: https://github.com/
    username: x-access-token
    password: ${{ secrets.MY_GITHUB_PAT }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - github
